name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      GOTOOLCHAIN: go1.25.0+auto
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
          go test ./... -coverprofile=coverage.out
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout 5m
          skip-pkg-cache: true
          skip-build-cache: true

  examples-build:
    name: Build Example - ${{ matrix.function }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        function:
          - examples/hello
          - examples/client
          - examples/blobby
          - examples/socket-client
          - examples/socket-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install wash
        uses: wasmCloud/setup-wash-action@main
        with:
          wash-version: wash-v2.0.0-rc.8
      - name: Install componentize-go
        uses: bytecodealliance/componentize-go/.github/actions/setup-componentize-go@main
        with:
          version: canary
      - name: Run Build
        working-directory: ${{ matrix.function }}
        run: |
          make build