name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
          go test ./... -coverprofile=coverage.out
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

  examples-build:
    name: Build Example
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - examples/hello
          - examples/client
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Wash - ${{ matrix.function }}
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: wash
          git: https://github.com/wasmCloud/wasmCloud
          tag: wash-v2.0.0-rc.8
      - name: Install componentize-go
        uses: taiki-e/cache-cargo-install-action@v3
        with:
          tool: componentize-go
          git: https://github.com/bytecodealliance/componentize-go
          tag: canary
      - name: Run Build
        working-directory: ${{ matrix.function }}
        run: |
          make build